import * as z from "zod";
export declare const PermissionFlagSchema: <PermissionType extends "org_rename" | "org_manage_settings" | "org_manage_auth_settings" | "org_manage_billing" | "org_manage_users" | "org_manage_user_devices" | "org_invite_users_to_permitted_apps" | "org_approve_devices_for_permitted" | "org_manage_cli_users" | "org_create_cli_users_for_permitted_apps" | "org_manage_app_roles" | "org_manage_org_roles" | "org_manage_environment_roles" | "org_manage_teams" | "org_manage_app_groups" | "org_manage_block_groups" | "org_read_logs" | "org_manage_firewall" | "org_generate_recovery_key" | "org_clear_tokens" | "org_archive_import_export" | "org_manage_integrations" | "org_delete" | "apps_create" | "apps_delete" | "apps_read_permitted" | "blocks_create" | "blocks_read_all" | "blocks_rename" | "blocks_manage_settings" | "blocks_write_envs_all" | "blocks_write_envs_permitted" | "blocks_manage_connections_permitted" | "blocks_manage_environments" | "blocks_delete" | "self_hosted_upgrade" | "self_hosted_manage_host" | "self_hosted_read_host_logs" | "app_read" | "app_rename" | "app_manage_settings" | "app_manage_users" | "app_approve_user_devices" | "app_manage_cli_users" | "app_read_own_locals" | "app_read_user_locals" | "app_read_user_locals_history" | "app_write_user_locals" | "app_manage_blocks" | "app_manage_environments" | "app_manage_servers" | "app_manage_local_keys" | "app_read_logs" | "app_manage_included_roles" | "app_manage_firewall" | "write" | "write_branches" | "read" | "read_inherits" | "read_meta" | "read_history" | "read_branches" | "read_branches_inherits" | "read_branches_meta" | "read_branches_history">(permissions: PermissionType[]) => z.ZodObject<Record<PermissionType, z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>, {
    strict: true;
}, { [k_10 in keyof ({ [k_3 in ((Record<PermissionType, z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>> extends infer T_2 extends import("zod/lib/src/types/base").ZodRawShape ? { [k_2 in keyof T_2]: Record<PermissionType, z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>[k_2]["_type"]; } : never) extends infer T ? { [k in keyof T]: undefined extends (Record<PermissionType, z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>> extends infer T_1 extends import("zod/lib/src/types/base").ZodRawShape ? { [k_1 in keyof T_1]: Record<PermissionType, z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>[k_1]["_type"]; } : never)[k] ? k : never; } : never)[PermissionType]]?: (Record<PermissionType, z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>> extends infer T_3 extends import("zod/lib/src/types/base").ZodRawShape ? { [k_4 in keyof T_3]: Record<PermissionType, z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>[k_4]["_type"]; } : never)[k_3]; } & { [k_8 in Exclude<PermissionType, ((Record<PermissionType, z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>> extends infer T_6 extends import("zod/lib/src/types/base").ZodRawShape ? { [k_7 in keyof T_6]: Record<PermissionType, z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>[k_7]["_type"]; } : never) extends infer T_4 ? { [k_5 in keyof T_4]: undefined extends (Record<PermissionType, z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>> extends infer T_5 extends import("zod/lib/src/types/base").ZodRawShape ? { [k_6 in keyof T_5]: Record<PermissionType, z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>[k_6]["_type"]; } : never)[k_5] ? k_5 : never; } : never)[PermissionType]>]: (Record<PermissionType, z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>> extends infer T_7 extends import("zod/lib/src/types/base").ZodRawShape ? { [k_9 in keyof T_7]: Record<PermissionType, z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>[k_9]["_type"]; } : never)[k_8]; })]: ({ [k_14 in ((Record<PermissionType, z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>> extends infer T_10 extends import("zod/lib/src/types/base").ZodRawShape ? { [k_13 in keyof T_10]: Record<PermissionType, z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>[k_13]["_type"]; } : never) extends infer T_8 ? { [k_11 in keyof T_8]: undefined extends (Record<PermissionType, z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>> extends infer T_9 extends import("zod/lib/src/types/base").ZodRawShape ? { [k_12 in keyof T_9]: Record<PermissionType, z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>[k_12]["_type"]; } : never)[k_11] ? k_11 : never; } : never)[PermissionType]]?: (Record<PermissionType, z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>> extends infer T_11 extends import("zod/lib/src/types/base").ZodRawShape ? { [k_15 in keyof T_11]: Record<PermissionType, z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>[k_15]["_type"]; } : never)[k_14]; } & { [k_19 in Exclude<PermissionType, ((Record<PermissionType, z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>> extends infer T_14 extends import("zod/lib/src/types/base").ZodRawShape ? { [k_18 in keyof T_14]: Record<PermissionType, z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>[k_18]["_type"]; } : never) extends infer T_12 ? { [k_16 in keyof T_12]: undefined extends (Record<PermissionType, z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>> extends infer T_13 extends import("zod/lib/src/types/base").ZodRawShape ? { [k_17 in keyof T_13]: Record<PermissionType, z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>[k_17]["_type"]; } : never)[k_16] ? k_16 : never; } : never)[PermissionType]>]: (Record<PermissionType, z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>> extends infer T_15 extends import("zod/lib/src/types/base").ZodRawShape ? { [k_20 in keyof T_15]: Record<PermissionType, z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>[k_20]["_type"]; } : never)[k_19]; })[k_10]; }>, OrgPermissionFlagSchema: z.ZodObject<Record<"org_rename" | "org_manage_settings" | "org_manage_auth_settings" | "org_manage_billing" | "org_manage_users" | "org_manage_user_devices" | "org_invite_users_to_permitted_apps" | "org_approve_devices_for_permitted" | "org_manage_cli_users" | "org_create_cli_users_for_permitted_apps" | "org_manage_app_roles" | "org_manage_org_roles" | "org_manage_environment_roles" | "org_manage_teams" | "org_manage_app_groups" | "org_manage_block_groups" | "org_read_logs" | "org_manage_firewall" | "org_generate_recovery_key" | "org_clear_tokens" | "org_archive_import_export" | "org_manage_integrations" | "org_delete" | "apps_create" | "apps_delete" | "apps_read_permitted" | "blocks_create" | "blocks_read_all" | "blocks_rename" | "blocks_manage_settings" | "blocks_write_envs_all" | "blocks_write_envs_permitted" | "blocks_manage_connections_permitted" | "blocks_manage_environments" | "blocks_delete" | "self_hosted_upgrade" | "self_hosted_manage_host" | "self_hosted_read_host_logs", z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>, {
    strict: true;
}, {
    org_rename?: true;
    org_manage_settings?: true;
    org_manage_auth_settings?: true;
    org_manage_billing?: true;
    org_manage_users?: true;
    org_manage_user_devices?: true;
    org_invite_users_to_permitted_apps?: true;
    org_approve_devices_for_permitted?: true;
    org_manage_cli_users?: true;
    org_create_cli_users_for_permitted_apps?: true;
    org_manage_app_roles?: true;
    org_manage_org_roles?: true;
    org_manage_environment_roles?: true;
    org_manage_teams?: true;
    org_manage_app_groups?: true;
    org_manage_block_groups?: true;
    org_read_logs?: true;
    org_manage_firewall?: true;
    org_generate_recovery_key?: true;
    org_clear_tokens?: true;
    org_archive_import_export?: true;
    org_manage_integrations?: true;
    org_delete?: true;
    apps_create?: true;
    apps_delete?: true;
    apps_read_permitted?: true;
    blocks_create?: true;
    blocks_read_all?: true;
    blocks_rename?: true;
    blocks_manage_settings?: true;
    blocks_write_envs_all?: true;
    blocks_write_envs_permitted?: true;
    blocks_manage_connections_permitted?: true;
    blocks_manage_environments?: true;
    blocks_delete?: true;
    self_hosted_upgrade?: true;
    self_hosted_manage_host?: true;
    self_hosted_read_host_logs?: true;
}>, AppPermissionFlagSchema: z.ZodObject<Record<"app_read" | "app_rename" | "app_manage_settings" | "app_manage_users" | "app_approve_user_devices" | "app_manage_cli_users" | "app_read_own_locals" | "app_read_user_locals" | "app_read_user_locals_history" | "app_write_user_locals" | "app_manage_blocks" | "app_manage_environments" | "app_manage_servers" | "app_manage_local_keys" | "app_read_logs" | "app_manage_included_roles" | "app_manage_firewall", z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>, {
    strict: true;
}, {
    app_read?: true;
    app_rename?: true;
    app_manage_settings?: true;
    app_manage_users?: true;
    app_approve_user_devices?: true;
    app_manage_cli_users?: true;
    app_read_own_locals?: true;
    app_read_user_locals?: true;
    app_read_user_locals_history?: true;
    app_write_user_locals?: true;
    app_manage_blocks?: true;
    app_manage_environments?: true;
    app_manage_servers?: true;
    app_manage_local_keys?: true;
    app_read_logs?: true;
    app_manage_included_roles?: true;
    app_manage_firewall?: true;
}>, EnvironmentPermissionFlagSchema: z.ZodObject<Record<"write" | "write_branches" | "read" | "read_inherits" | "read_meta" | "read_history" | "read_branches" | "read_branches_inherits" | "read_branches_meta" | "read_branches_history", z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>, {
    strict: true;
}, {
    write?: true;
    write_branches?: true;
    read?: true;
    read_inherits?: true;
    read_meta?: true;
    read_history?: true;
    read_branches?: true;
    read_branches_inherits?: true;
    read_branches_meta?: true;
    read_branches_history?: true;
}>;
export type OrgAccessScope = "all" | {
    userIds?: Set<string> | "all";
    deviceIds?: Set<string> | "all";
    envParentIds?: Set<string> | "all";
    environmentIds?: Set<string> | "all";
    keyableParentIds?: Set<string> | "all";
};
export type OrgAccessSet = z.infer<typeof OrgAccessSetSchema>;
export declare const OrgAccessSetSchema: z.ZodObject<{
    org: z.ZodUnion<[z.ZodObject<{
        users: z.ZodUnion<[z.ZodRecord<z.ZodObject<Record<"org_rename" | "org_manage_settings" | "org_manage_auth_settings" | "org_manage_billing" | "org_manage_users" | "org_manage_user_devices" | "org_invite_users_to_permitted_apps" | "org_approve_devices_for_permitted" | "org_manage_cli_users" | "org_create_cli_users_for_permitted_apps" | "org_manage_app_roles" | "org_manage_org_roles" | "org_manage_environment_roles" | "org_manage_teams" | "org_manage_app_groups" | "org_manage_block_groups" | "org_read_logs" | "org_manage_firewall" | "org_generate_recovery_key" | "org_clear_tokens" | "org_archive_import_export" | "org_manage_integrations" | "org_delete" | "apps_create" | "apps_delete" | "apps_read_permitted" | "blocks_create" | "blocks_read_all" | "blocks_rename" | "blocks_manage_settings" | "blocks_write_envs_all" | "blocks_write_envs_permitted" | "blocks_manage_connections_permitted" | "blocks_manage_environments" | "blocks_delete" | "self_hosted_upgrade" | "self_hosted_manage_host" | "self_hosted_read_host_logs", z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>, {
            strict: true;
        }, {
            org_rename?: true;
            org_manage_settings?: true;
            org_manage_auth_settings?: true;
            org_manage_billing?: true;
            org_manage_users?: true;
            org_manage_user_devices?: true;
            org_invite_users_to_permitted_apps?: true;
            org_approve_devices_for_permitted?: true;
            org_manage_cli_users?: true;
            org_create_cli_users_for_permitted_apps?: true;
            org_manage_app_roles?: true;
            org_manage_org_roles?: true;
            org_manage_environment_roles?: true;
            org_manage_teams?: true;
            org_manage_app_groups?: true;
            org_manage_block_groups?: true;
            org_read_logs?: true;
            org_manage_firewall?: true;
            org_generate_recovery_key?: true;
            org_clear_tokens?: true;
            org_archive_import_export?: true;
            org_manage_integrations?: true;
            org_delete?: true;
            apps_create?: true;
            apps_delete?: true;
            apps_read_permitted?: true;
            blocks_create?: true;
            blocks_read_all?: true;
            blocks_rename?: true;
            blocks_manage_settings?: true;
            blocks_write_envs_all?: true;
            blocks_write_envs_permitted?: true;
            blocks_manage_connections_permitted?: true;
            blocks_manage_environments?: true;
            blocks_delete?: true;
            self_hosted_upgrade?: true;
            self_hosted_manage_host?: true;
            self_hosted_read_host_logs?: true;
        }>>, z.ZodUndefined]>;
        devices: z.ZodUnion<[z.ZodRecord<z.ZodObject<Record<"org_rename" | "org_manage_settings" | "org_manage_auth_settings" | "org_manage_billing" | "org_manage_users" | "org_manage_user_devices" | "org_invite_users_to_permitted_apps" | "org_approve_devices_for_permitted" | "org_manage_cli_users" | "org_create_cli_users_for_permitted_apps" | "org_manage_app_roles" | "org_manage_org_roles" | "org_manage_environment_roles" | "org_manage_teams" | "org_manage_app_groups" | "org_manage_block_groups" | "org_read_logs" | "org_manage_firewall" | "org_generate_recovery_key" | "org_clear_tokens" | "org_archive_import_export" | "org_manage_integrations" | "org_delete" | "apps_create" | "apps_delete" | "apps_read_permitted" | "blocks_create" | "blocks_read_all" | "blocks_rename" | "blocks_manage_settings" | "blocks_write_envs_all" | "blocks_write_envs_permitted" | "blocks_manage_connections_permitted" | "blocks_manage_environments" | "blocks_delete" | "self_hosted_upgrade" | "self_hosted_manage_host" | "self_hosted_read_host_logs", z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>, {
            strict: true;
        }, {
            org_rename?: true;
            org_manage_settings?: true;
            org_manage_auth_settings?: true;
            org_manage_billing?: true;
            org_manage_users?: true;
            org_manage_user_devices?: true;
            org_invite_users_to_permitted_apps?: true;
            org_approve_devices_for_permitted?: true;
            org_manage_cli_users?: true;
            org_create_cli_users_for_permitted_apps?: true;
            org_manage_app_roles?: true;
            org_manage_org_roles?: true;
            org_manage_environment_roles?: true;
            org_manage_teams?: true;
            org_manage_app_groups?: true;
            org_manage_block_groups?: true;
            org_read_logs?: true;
            org_manage_firewall?: true;
            org_generate_recovery_key?: true;
            org_clear_tokens?: true;
            org_archive_import_export?: true;
            org_manage_integrations?: true;
            org_delete?: true;
            apps_create?: true;
            apps_delete?: true;
            apps_read_permitted?: true;
            blocks_create?: true;
            blocks_read_all?: true;
            blocks_rename?: true;
            blocks_manage_settings?: true;
            blocks_write_envs_all?: true;
            blocks_write_envs_permitted?: true;
            blocks_manage_connections_permitted?: true;
            blocks_manage_environments?: true;
            blocks_delete?: true;
            self_hosted_upgrade?: true;
            self_hosted_manage_host?: true;
            self_hosted_read_host_logs?: true;
        }>>, z.ZodUndefined]>;
    }, {
        strict: true;
    }, {
        users?: Record<string, {
            org_rename?: true;
            org_manage_settings?: true;
            org_manage_auth_settings?: true;
            org_manage_billing?: true;
            org_manage_users?: true;
            org_manage_user_devices?: true;
            org_invite_users_to_permitted_apps?: true;
            org_approve_devices_for_permitted?: true;
            org_manage_cli_users?: true;
            org_create_cli_users_for_permitted_apps?: true;
            org_manage_app_roles?: true;
            org_manage_org_roles?: true;
            org_manage_environment_roles?: true;
            org_manage_teams?: true;
            org_manage_app_groups?: true;
            org_manage_block_groups?: true;
            org_read_logs?: true;
            org_manage_firewall?: true;
            org_generate_recovery_key?: true;
            org_clear_tokens?: true;
            org_archive_import_export?: true;
            org_manage_integrations?: true;
            org_delete?: true;
            apps_create?: true;
            apps_delete?: true;
            apps_read_permitted?: true;
            blocks_create?: true;
            blocks_read_all?: true;
            blocks_rename?: true;
            blocks_manage_settings?: true;
            blocks_write_envs_all?: true;
            blocks_write_envs_permitted?: true;
            blocks_manage_connections_permitted?: true;
            blocks_manage_environments?: true;
            blocks_delete?: true;
            self_hosted_upgrade?: true;
            self_hosted_manage_host?: true;
            self_hosted_read_host_logs?: true;
        }>;
        devices?: Record<string, {
            org_rename?: true;
            org_manage_settings?: true;
            org_manage_auth_settings?: true;
            org_manage_billing?: true;
            org_manage_users?: true;
            org_manage_user_devices?: true;
            org_invite_users_to_permitted_apps?: true;
            org_approve_devices_for_permitted?: true;
            org_manage_cli_users?: true;
            org_create_cli_users_for_permitted_apps?: true;
            org_manage_app_roles?: true;
            org_manage_org_roles?: true;
            org_manage_environment_roles?: true;
            org_manage_teams?: true;
            org_manage_app_groups?: true;
            org_manage_block_groups?: true;
            org_read_logs?: true;
            org_manage_firewall?: true;
            org_generate_recovery_key?: true;
            org_clear_tokens?: true;
            org_archive_import_export?: true;
            org_manage_integrations?: true;
            org_delete?: true;
            apps_create?: true;
            apps_delete?: true;
            apps_read_permitted?: true;
            blocks_create?: true;
            blocks_read_all?: true;
            blocks_rename?: true;
            blocks_manage_settings?: true;
            blocks_write_envs_all?: true;
            blocks_write_envs_permitted?: true;
            blocks_manage_connections_permitted?: true;
            blocks_manage_environments?: true;
            blocks_delete?: true;
            self_hosted_upgrade?: true;
            self_hosted_manage_host?: true;
            self_hosted_read_host_logs?: true;
        }>;
    }>, z.ZodUndefined]>;
    apps: z.ZodUnion<[z.ZodRecord<z.ZodObject<{
        users: z.ZodUnion<[z.ZodRecord<z.ZodObject<Record<"app_read" | "app_rename" | "app_manage_settings" | "app_manage_users" | "app_approve_user_devices" | "app_manage_cli_users" | "app_read_own_locals" | "app_read_user_locals" | "app_read_user_locals_history" | "app_write_user_locals" | "app_manage_blocks" | "app_manage_environments" | "app_manage_servers" | "app_manage_local_keys" | "app_read_logs" | "app_manage_included_roles" | "app_manage_firewall", z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>, {
            strict: true;
        }, {
            app_read?: true;
            app_rename?: true;
            app_manage_settings?: true;
            app_manage_users?: true;
            app_approve_user_devices?: true;
            app_manage_cli_users?: true;
            app_read_own_locals?: true;
            app_read_user_locals?: true;
            app_read_user_locals_history?: true;
            app_write_user_locals?: true;
            app_manage_blocks?: true;
            app_manage_environments?: true;
            app_manage_servers?: true;
            app_manage_local_keys?: true;
            app_read_logs?: true;
            app_manage_included_roles?: true;
            app_manage_firewall?: true;
        }>>, z.ZodUndefined]>;
        devices: z.ZodUnion<[z.ZodRecord<z.ZodObject<Record<"app_read" | "app_rename" | "app_manage_settings" | "app_manage_users" | "app_approve_user_devices" | "app_manage_cli_users" | "app_read_own_locals" | "app_read_user_locals" | "app_read_user_locals_history" | "app_write_user_locals" | "app_manage_blocks" | "app_manage_environments" | "app_manage_servers" | "app_manage_local_keys" | "app_read_logs" | "app_manage_included_roles" | "app_manage_firewall", z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>, {
            strict: true;
        }, {
            app_read?: true;
            app_rename?: true;
            app_manage_settings?: true;
            app_manage_users?: true;
            app_approve_user_devices?: true;
            app_manage_cli_users?: true;
            app_read_own_locals?: true;
            app_read_user_locals?: true;
            app_read_user_locals_history?: true;
            app_write_user_locals?: true;
            app_manage_blocks?: true;
            app_manage_environments?: true;
            app_manage_servers?: true;
            app_manage_local_keys?: true;
            app_read_logs?: true;
            app_manage_included_roles?: true;
            app_manage_firewall?: true;
        }>>, z.ZodUndefined]>;
    }, {
        strict: true;
    }, {
        users?: Record<string, {
            app_read?: true;
            app_rename?: true;
            app_manage_settings?: true;
            app_manage_users?: true;
            app_approve_user_devices?: true;
            app_manage_cli_users?: true;
            app_read_own_locals?: true;
            app_read_user_locals?: true;
            app_read_user_locals_history?: true;
            app_write_user_locals?: true;
            app_manage_blocks?: true;
            app_manage_environments?: true;
            app_manage_servers?: true;
            app_manage_local_keys?: true;
            app_read_logs?: true;
            app_manage_included_roles?: true;
            app_manage_firewall?: true;
        }>;
        devices?: Record<string, {
            app_read?: true;
            app_rename?: true;
            app_manage_settings?: true;
            app_manage_users?: true;
            app_approve_user_devices?: true;
            app_manage_cli_users?: true;
            app_read_own_locals?: true;
            app_read_user_locals?: true;
            app_read_user_locals_history?: true;
            app_write_user_locals?: true;
            app_manage_blocks?: true;
            app_manage_environments?: true;
            app_manage_servers?: true;
            app_manage_local_keys?: true;
            app_read_logs?: true;
            app_manage_included_roles?: true;
            app_manage_firewall?: true;
        }>;
    }>>, z.ZodUndefined]>;
    environments: z.ZodUnion<[z.ZodRecord<z.ZodObject<{
        servers: z.ZodUnion<[z.ZodRecord<z.ZodString>, z.ZodUndefined]>;
        localKeys: z.ZodUnion<[z.ZodRecord<z.ZodString>, z.ZodUndefined]>;
        users: z.ZodUnion<[z.ZodRecord<z.ZodObject<Record<"write" | "write_branches" | "read" | "read_inherits" | "read_meta" | "read_history" | "read_branches" | "read_branches_inherits" | "read_branches_meta" | "read_branches_history", z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>, {
            strict: true;
        }, {
            write?: true;
            write_branches?: true;
            read?: true;
            read_inherits?: true;
            read_meta?: true;
            read_history?: true;
            read_branches?: true;
            read_branches_inherits?: true;
            read_branches_meta?: true;
            read_branches_history?: true;
        }>>, z.ZodUndefined]>;
        devices: z.ZodUnion<[z.ZodRecord<z.ZodObject<Record<"write" | "write_branches" | "read" | "read_inherits" | "read_meta" | "read_history" | "read_branches" | "read_branches_inherits" | "read_branches_meta" | "read_branches_history", z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>, {
            strict: true;
        }, {
            write?: true;
            write_branches?: true;
            read?: true;
            read_inherits?: true;
            read_meta?: true;
            read_history?: true;
            read_branches?: true;
            read_branches_inherits?: true;
            read_branches_meta?: true;
            read_branches_history?: true;
        }>>, z.ZodUndefined]>;
    }, {
        strict: true;
    }, {
        users?: Record<string, {
            write?: true;
            write_branches?: true;
            read?: true;
            read_inherits?: true;
            read_meta?: true;
            read_history?: true;
            read_branches?: true;
            read_branches_inherits?: true;
            read_branches_meta?: true;
            read_branches_history?: true;
        }>;
        devices?: Record<string, {
            write?: true;
            write_branches?: true;
            read?: true;
            read_inherits?: true;
            read_meta?: true;
            read_history?: true;
            read_branches?: true;
            read_branches_inherits?: true;
            read_branches_meta?: true;
            read_branches_history?: true;
        }>;
        servers?: Record<string, string>;
        localKeys?: Record<string, string>;
    }>>, z.ZodUndefined]>;
}, {
    strict: true;
}, {
    org?: {
        users?: Record<string, {
            org_rename?: true;
            org_manage_settings?: true;
            org_manage_auth_settings?: true;
            org_manage_billing?: true;
            org_manage_users?: true;
            org_manage_user_devices?: true;
            org_invite_users_to_permitted_apps?: true;
            org_approve_devices_for_permitted?: true;
            org_manage_cli_users?: true;
            org_create_cli_users_for_permitted_apps?: true;
            org_manage_app_roles?: true;
            org_manage_org_roles?: true;
            org_manage_environment_roles?: true;
            org_manage_teams?: true;
            org_manage_app_groups?: true;
            org_manage_block_groups?: true;
            org_read_logs?: true;
            org_manage_firewall?: true;
            org_generate_recovery_key?: true;
            org_clear_tokens?: true;
            org_archive_import_export?: true;
            org_manage_integrations?: true;
            org_delete?: true;
            apps_create?: true;
            apps_delete?: true;
            apps_read_permitted?: true;
            blocks_create?: true;
            blocks_read_all?: true;
            blocks_rename?: true;
            blocks_manage_settings?: true;
            blocks_write_envs_all?: true;
            blocks_write_envs_permitted?: true;
            blocks_manage_connections_permitted?: true;
            blocks_manage_environments?: true;
            blocks_delete?: true;
            self_hosted_upgrade?: true;
            self_hosted_manage_host?: true;
            self_hosted_read_host_logs?: true;
        }>;
        devices?: Record<string, {
            org_rename?: true;
            org_manage_settings?: true;
            org_manage_auth_settings?: true;
            org_manage_billing?: true;
            org_manage_users?: true;
            org_manage_user_devices?: true;
            org_invite_users_to_permitted_apps?: true;
            org_approve_devices_for_permitted?: true;
            org_manage_cli_users?: true;
            org_create_cli_users_for_permitted_apps?: true;
            org_manage_app_roles?: true;
            org_manage_org_roles?: true;
            org_manage_environment_roles?: true;
            org_manage_teams?: true;
            org_manage_app_groups?: true;
            org_manage_block_groups?: true;
            org_read_logs?: true;
            org_manage_firewall?: true;
            org_generate_recovery_key?: true;
            org_clear_tokens?: true;
            org_archive_import_export?: true;
            org_manage_integrations?: true;
            org_delete?: true;
            apps_create?: true;
            apps_delete?: true;
            apps_read_permitted?: true;
            blocks_create?: true;
            blocks_read_all?: true;
            blocks_rename?: true;
            blocks_manage_settings?: true;
            blocks_write_envs_all?: true;
            blocks_write_envs_permitted?: true;
            blocks_manage_connections_permitted?: true;
            blocks_manage_environments?: true;
            blocks_delete?: true;
            self_hosted_upgrade?: true;
            self_hosted_manage_host?: true;
            self_hosted_read_host_logs?: true;
        }>;
    };
    apps?: Record<string, {
        users?: Record<string, {
            app_read?: true;
            app_rename?: true;
            app_manage_settings?: true;
            app_manage_users?: true;
            app_approve_user_devices?: true;
            app_manage_cli_users?: true;
            app_read_own_locals?: true;
            app_read_user_locals?: true;
            app_read_user_locals_history?: true;
            app_write_user_locals?: true;
            app_manage_blocks?: true;
            app_manage_environments?: true;
            app_manage_servers?: true;
            app_manage_local_keys?: true;
            app_read_logs?: true;
            app_manage_included_roles?: true;
            app_manage_firewall?: true;
        }>;
        devices?: Record<string, {
            app_read?: true;
            app_rename?: true;
            app_manage_settings?: true;
            app_manage_users?: true;
            app_approve_user_devices?: true;
            app_manage_cli_users?: true;
            app_read_own_locals?: true;
            app_read_user_locals?: true;
            app_read_user_locals_history?: true;
            app_write_user_locals?: true;
            app_manage_blocks?: true;
            app_manage_environments?: true;
            app_manage_servers?: true;
            app_manage_local_keys?: true;
            app_read_logs?: true;
            app_manage_included_roles?: true;
            app_manage_firewall?: true;
        }>;
    }>;
    environments?: Record<string, {
        users?: Record<string, {
            write?: true;
            write_branches?: true;
            read?: true;
            read_inherits?: true;
            read_meta?: true;
            read_history?: true;
            read_branches?: true;
            read_branches_inherits?: true;
            read_branches_meta?: true;
            read_branches_history?: true;
        }>;
        devices?: Record<string, {
            write?: true;
            write_branches?: true;
            read?: true;
            read_inherits?: true;
            read_meta?: true;
            read_history?: true;
            read_branches?: true;
            read_branches_inherits?: true;
            read_branches_meta?: true;
            read_branches_history?: true;
        }>;
        servers?: Record<string, string>;
        localKeys?: Record<string, string>;
    }>;
}>;
export declare const OrgAccessUpdatedSchema: z.ZodObject<{
    granted: z.ZodUnion<[z.ZodObject<{
        org: z.ZodUnion<[z.ZodObject<{
            users: z.ZodUnion<[z.ZodRecord<z.ZodObject<Record<"org_rename" | "org_manage_settings" | "org_manage_auth_settings" | "org_manage_billing" | "org_manage_users" | "org_manage_user_devices" | "org_invite_users_to_permitted_apps" | "org_approve_devices_for_permitted" | "org_manage_cli_users" | "org_create_cli_users_for_permitted_apps" | "org_manage_app_roles" | "org_manage_org_roles" | "org_manage_environment_roles" | "org_manage_teams" | "org_manage_app_groups" | "org_manage_block_groups" | "org_read_logs" | "org_manage_firewall" | "org_generate_recovery_key" | "org_clear_tokens" | "org_archive_import_export" | "org_manage_integrations" | "org_delete" | "apps_create" | "apps_delete" | "apps_read_permitted" | "blocks_create" | "blocks_read_all" | "blocks_rename" | "blocks_manage_settings" | "blocks_write_envs_all" | "blocks_write_envs_permitted" | "blocks_manage_connections_permitted" | "blocks_manage_environments" | "blocks_delete" | "self_hosted_upgrade" | "self_hosted_manage_host" | "self_hosted_read_host_logs", z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>, {
                strict: true;
            }, {
                org_rename?: true;
                org_manage_settings?: true;
                org_manage_auth_settings?: true;
                org_manage_billing?: true;
                org_manage_users?: true;
                org_manage_user_devices?: true;
                org_invite_users_to_permitted_apps?: true;
                org_approve_devices_for_permitted?: true;
                org_manage_cli_users?: true;
                org_create_cli_users_for_permitted_apps?: true;
                org_manage_app_roles?: true;
                org_manage_org_roles?: true;
                org_manage_environment_roles?: true;
                org_manage_teams?: true;
                org_manage_app_groups?: true;
                org_manage_block_groups?: true;
                org_read_logs?: true;
                org_manage_firewall?: true;
                org_generate_recovery_key?: true;
                org_clear_tokens?: true;
                org_archive_import_export?: true;
                org_manage_integrations?: true;
                org_delete?: true;
                apps_create?: true;
                apps_delete?: true;
                apps_read_permitted?: true;
                blocks_create?: true;
                blocks_read_all?: true;
                blocks_rename?: true;
                blocks_manage_settings?: true;
                blocks_write_envs_all?: true;
                blocks_write_envs_permitted?: true;
                blocks_manage_connections_permitted?: true;
                blocks_manage_environments?: true;
                blocks_delete?: true;
                self_hosted_upgrade?: true;
                self_hosted_manage_host?: true;
                self_hosted_read_host_logs?: true;
            }>>, z.ZodUndefined]>;
            devices: z.ZodUnion<[z.ZodRecord<z.ZodObject<Record<"org_rename" | "org_manage_settings" | "org_manage_auth_settings" | "org_manage_billing" | "org_manage_users" | "org_manage_user_devices" | "org_invite_users_to_permitted_apps" | "org_approve_devices_for_permitted" | "org_manage_cli_users" | "org_create_cli_users_for_permitted_apps" | "org_manage_app_roles" | "org_manage_org_roles" | "org_manage_environment_roles" | "org_manage_teams" | "org_manage_app_groups" | "org_manage_block_groups" | "org_read_logs" | "org_manage_firewall" | "org_generate_recovery_key" | "org_clear_tokens" | "org_archive_import_export" | "org_manage_integrations" | "org_delete" | "apps_create" | "apps_delete" | "apps_read_permitted" | "blocks_create" | "blocks_read_all" | "blocks_rename" | "blocks_manage_settings" | "blocks_write_envs_all" | "blocks_write_envs_permitted" | "blocks_manage_connections_permitted" | "blocks_manage_environments" | "blocks_delete" | "self_hosted_upgrade" | "self_hosted_manage_host" | "self_hosted_read_host_logs", z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>, {
                strict: true;
            }, {
                org_rename?: true;
                org_manage_settings?: true;
                org_manage_auth_settings?: true;
                org_manage_billing?: true;
                org_manage_users?: true;
                org_manage_user_devices?: true;
                org_invite_users_to_permitted_apps?: true;
                org_approve_devices_for_permitted?: true;
                org_manage_cli_users?: true;
                org_create_cli_users_for_permitted_apps?: true;
                org_manage_app_roles?: true;
                org_manage_org_roles?: true;
                org_manage_environment_roles?: true;
                org_manage_teams?: true;
                org_manage_app_groups?: true;
                org_manage_block_groups?: true;
                org_read_logs?: true;
                org_manage_firewall?: true;
                org_generate_recovery_key?: true;
                org_clear_tokens?: true;
                org_archive_import_export?: true;
                org_manage_integrations?: true;
                org_delete?: true;
                apps_create?: true;
                apps_delete?: true;
                apps_read_permitted?: true;
                blocks_create?: true;
                blocks_read_all?: true;
                blocks_rename?: true;
                blocks_manage_settings?: true;
                blocks_write_envs_all?: true;
                blocks_write_envs_permitted?: true;
                blocks_manage_connections_permitted?: true;
                blocks_manage_environments?: true;
                blocks_delete?: true;
                self_hosted_upgrade?: true;
                self_hosted_manage_host?: true;
                self_hosted_read_host_logs?: true;
            }>>, z.ZodUndefined]>;
        }, {
            strict: true;
        }, {
            users?: Record<string, {
                org_rename?: true;
                org_manage_settings?: true;
                org_manage_auth_settings?: true;
                org_manage_billing?: true;
                org_manage_users?: true;
                org_manage_user_devices?: true;
                org_invite_users_to_permitted_apps?: true;
                org_approve_devices_for_permitted?: true;
                org_manage_cli_users?: true;
                org_create_cli_users_for_permitted_apps?: true;
                org_manage_app_roles?: true;
                org_manage_org_roles?: true;
                org_manage_environment_roles?: true;
                org_manage_teams?: true;
                org_manage_app_groups?: true;
                org_manage_block_groups?: true;
                org_read_logs?: true;
                org_manage_firewall?: true;
                org_generate_recovery_key?: true;
                org_clear_tokens?: true;
                org_archive_import_export?: true;
                org_manage_integrations?: true;
                org_delete?: true;
                apps_create?: true;
                apps_delete?: true;
                apps_read_permitted?: true;
                blocks_create?: true;
                blocks_read_all?: true;
                blocks_rename?: true;
                blocks_manage_settings?: true;
                blocks_write_envs_all?: true;
                blocks_write_envs_permitted?: true;
                blocks_manage_connections_permitted?: true;
                blocks_manage_environments?: true;
                blocks_delete?: true;
                self_hosted_upgrade?: true;
                self_hosted_manage_host?: true;
                self_hosted_read_host_logs?: true;
            }>;
            devices?: Record<string, {
                org_rename?: true;
                org_manage_settings?: true;
                org_manage_auth_settings?: true;
                org_manage_billing?: true;
                org_manage_users?: true;
                org_manage_user_devices?: true;
                org_invite_users_to_permitted_apps?: true;
                org_approve_devices_for_permitted?: true;
                org_manage_cli_users?: true;
                org_create_cli_users_for_permitted_apps?: true;
                org_manage_app_roles?: true;
                org_manage_org_roles?: true;
                org_manage_environment_roles?: true;
                org_manage_teams?: true;
                org_manage_app_groups?: true;
                org_manage_block_groups?: true;
                org_read_logs?: true;
                org_manage_firewall?: true;
                org_generate_recovery_key?: true;
                org_clear_tokens?: true;
                org_archive_import_export?: true;
                org_manage_integrations?: true;
                org_delete?: true;
                apps_create?: true;
                apps_delete?: true;
                apps_read_permitted?: true;
                blocks_create?: true;
                blocks_read_all?: true;
                blocks_rename?: true;
                blocks_manage_settings?: true;
                blocks_write_envs_all?: true;
                blocks_write_envs_permitted?: true;
                blocks_manage_connections_permitted?: true;
                blocks_manage_environments?: true;
                blocks_delete?: true;
                self_hosted_upgrade?: true;
                self_hosted_manage_host?: true;
                self_hosted_read_host_logs?: true;
            }>;
        }>, z.ZodUndefined]>;
        apps: z.ZodUnion<[z.ZodRecord<z.ZodObject<{
            users: z.ZodUnion<[z.ZodRecord<z.ZodObject<Record<"app_read" | "app_rename" | "app_manage_settings" | "app_manage_users" | "app_approve_user_devices" | "app_manage_cli_users" | "app_read_own_locals" | "app_read_user_locals" | "app_read_user_locals_history" | "app_write_user_locals" | "app_manage_blocks" | "app_manage_environments" | "app_manage_servers" | "app_manage_local_keys" | "app_read_logs" | "app_manage_included_roles" | "app_manage_firewall", z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>, {
                strict: true;
            }, {
                app_read?: true;
                app_rename?: true;
                app_manage_settings?: true;
                app_manage_users?: true;
                app_approve_user_devices?: true;
                app_manage_cli_users?: true;
                app_read_own_locals?: true;
                app_read_user_locals?: true;
                app_read_user_locals_history?: true;
                app_write_user_locals?: true;
                app_manage_blocks?: true;
                app_manage_environments?: true;
                app_manage_servers?: true;
                app_manage_local_keys?: true;
                app_read_logs?: true;
                app_manage_included_roles?: true;
                app_manage_firewall?: true;
            }>>, z.ZodUndefined]>;
            devices: z.ZodUnion<[z.ZodRecord<z.ZodObject<Record<"app_read" | "app_rename" | "app_manage_settings" | "app_manage_users" | "app_approve_user_devices" | "app_manage_cli_users" | "app_read_own_locals" | "app_read_user_locals" | "app_read_user_locals_history" | "app_write_user_locals" | "app_manage_blocks" | "app_manage_environments" | "app_manage_servers" | "app_manage_local_keys" | "app_read_logs" | "app_manage_included_roles" | "app_manage_firewall", z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>, {
                strict: true;
            }, {
                app_read?: true;
                app_rename?: true;
                app_manage_settings?: true;
                app_manage_users?: true;
                app_approve_user_devices?: true;
                app_manage_cli_users?: true;
                app_read_own_locals?: true;
                app_read_user_locals?: true;
                app_read_user_locals_history?: true;
                app_write_user_locals?: true;
                app_manage_blocks?: true;
                app_manage_environments?: true;
                app_manage_servers?: true;
                app_manage_local_keys?: true;
                app_read_logs?: true;
                app_manage_included_roles?: true;
                app_manage_firewall?: true;
            }>>, z.ZodUndefined]>;
        }, {
            strict: true;
        }, {
            users?: Record<string, {
                app_read?: true;
                app_rename?: true;
                app_manage_settings?: true;
                app_manage_users?: true;
                app_approve_user_devices?: true;
                app_manage_cli_users?: true;
                app_read_own_locals?: true;
                app_read_user_locals?: true;
                app_read_user_locals_history?: true;
                app_write_user_locals?: true;
                app_manage_blocks?: true;
                app_manage_environments?: true;
                app_manage_servers?: true;
                app_manage_local_keys?: true;
                app_read_logs?: true;
                app_manage_included_roles?: true;
                app_manage_firewall?: true;
            }>;
            devices?: Record<string, {
                app_read?: true;
                app_rename?: true;
                app_manage_settings?: true;
                app_manage_users?: true;
                app_approve_user_devices?: true;
                app_manage_cli_users?: true;
                app_read_own_locals?: true;
                app_read_user_locals?: true;
                app_read_user_locals_history?: true;
                app_write_user_locals?: true;
                app_manage_blocks?: true;
                app_manage_environments?: true;
                app_manage_servers?: true;
                app_manage_local_keys?: true;
                app_read_logs?: true;
                app_manage_included_roles?: true;
                app_manage_firewall?: true;
            }>;
        }>>, z.ZodUndefined]>;
        environments: z.ZodUnion<[z.ZodRecord<z.ZodObject<{
            servers: z.ZodUnion<[z.ZodRecord<z.ZodString>, z.ZodUndefined]>;
            localKeys: z.ZodUnion<[z.ZodRecord<z.ZodString>, z.ZodUndefined]>;
            users: z.ZodUnion<[z.ZodRecord<z.ZodObject<Record<"write" | "write_branches" | "read" | "read_inherits" | "read_meta" | "read_history" | "read_branches" | "read_branches_inherits" | "read_branches_meta" | "read_branches_history", z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>, {
                strict: true;
            }, {
                write?: true;
                write_branches?: true;
                read?: true;
                read_inherits?: true;
                read_meta?: true;
                read_history?: true;
                read_branches?: true;
                read_branches_inherits?: true;
                read_branches_meta?: true;
                read_branches_history?: true;
            }>>, z.ZodUndefined]>;
            devices: z.ZodUnion<[z.ZodRecord<z.ZodObject<Record<"write" | "write_branches" | "read" | "read_inherits" | "read_meta" | "read_history" | "read_branches" | "read_branches_inherits" | "read_branches_meta" | "read_branches_history", z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>, {
                strict: true;
            }, {
                write?: true;
                write_branches?: true;
                read?: true;
                read_inherits?: true;
                read_meta?: true;
                read_history?: true;
                read_branches?: true;
                read_branches_inherits?: true;
                read_branches_meta?: true;
                read_branches_history?: true;
            }>>, z.ZodUndefined]>;
        }, {
            strict: true;
        }, {
            users?: Record<string, {
                write?: true;
                write_branches?: true;
                read?: true;
                read_inherits?: true;
                read_meta?: true;
                read_history?: true;
                read_branches?: true;
                read_branches_inherits?: true;
                read_branches_meta?: true;
                read_branches_history?: true;
            }>;
            devices?: Record<string, {
                write?: true;
                write_branches?: true;
                read?: true;
                read_inherits?: true;
                read_meta?: true;
                read_history?: true;
                read_branches?: true;
                read_branches_inherits?: true;
                read_branches_meta?: true;
                read_branches_history?: true;
            }>;
            servers?: Record<string, string>;
            localKeys?: Record<string, string>;
        }>>, z.ZodUndefined]>;
    }, {
        strict: true;
    }, {
        org?: {
            users?: Record<string, {
                org_rename?: true;
                org_manage_settings?: true;
                org_manage_auth_settings?: true;
                org_manage_billing?: true;
                org_manage_users?: true;
                org_manage_user_devices?: true;
                org_invite_users_to_permitted_apps?: true;
                org_approve_devices_for_permitted?: true;
                org_manage_cli_users?: true;
                org_create_cli_users_for_permitted_apps?: true;
                org_manage_app_roles?: true;
                org_manage_org_roles?: true;
                org_manage_environment_roles?: true;
                org_manage_teams?: true;
                org_manage_app_groups?: true;
                org_manage_block_groups?: true;
                org_read_logs?: true;
                org_manage_firewall?: true;
                org_generate_recovery_key?: true;
                org_clear_tokens?: true;
                org_archive_import_export?: true;
                org_manage_integrations?: true;
                org_delete?: true;
                apps_create?: true;
                apps_delete?: true;
                apps_read_permitted?: true;
                blocks_create?: true;
                blocks_read_all?: true;
                blocks_rename?: true;
                blocks_manage_settings?: true;
                blocks_write_envs_all?: true;
                blocks_write_envs_permitted?: true;
                blocks_manage_connections_permitted?: true;
                blocks_manage_environments?: true;
                blocks_delete?: true;
                self_hosted_upgrade?: true;
                self_hosted_manage_host?: true;
                self_hosted_read_host_logs?: true;
            }>;
            devices?: Record<string, {
                org_rename?: true;
                org_manage_settings?: true;
                org_manage_auth_settings?: true;
                org_manage_billing?: true;
                org_manage_users?: true;
                org_manage_user_devices?: true;
                org_invite_users_to_permitted_apps?: true;
                org_approve_devices_for_permitted?: true;
                org_manage_cli_users?: true;
                org_create_cli_users_for_permitted_apps?: true;
                org_manage_app_roles?: true;
                org_manage_org_roles?: true;
                org_manage_environment_roles?: true;
                org_manage_teams?: true;
                org_manage_app_groups?: true;
                org_manage_block_groups?: true;
                org_read_logs?: true;
                org_manage_firewall?: true;
                org_generate_recovery_key?: true;
                org_clear_tokens?: true;
                org_archive_import_export?: true;
                org_manage_integrations?: true;
                org_delete?: true;
                apps_create?: true;
                apps_delete?: true;
                apps_read_permitted?: true;
                blocks_create?: true;
                blocks_read_all?: true;
                blocks_rename?: true;
                blocks_manage_settings?: true;
                blocks_write_envs_all?: true;
                blocks_write_envs_permitted?: true;
                blocks_manage_connections_permitted?: true;
                blocks_manage_environments?: true;
                blocks_delete?: true;
                self_hosted_upgrade?: true;
                self_hosted_manage_host?: true;
                self_hosted_read_host_logs?: true;
            }>;
        };
        apps?: Record<string, {
            users?: Record<string, {
                app_read?: true;
                app_rename?: true;
                app_manage_settings?: true;
                app_manage_users?: true;
                app_approve_user_devices?: true;
                app_manage_cli_users?: true;
                app_read_own_locals?: true;
                app_read_user_locals?: true;
                app_read_user_locals_history?: true;
                app_write_user_locals?: true;
                app_manage_blocks?: true;
                app_manage_environments?: true;
                app_manage_servers?: true;
                app_manage_local_keys?: true;
                app_read_logs?: true;
                app_manage_included_roles?: true;
                app_manage_firewall?: true;
            }>;
            devices?: Record<string, {
                app_read?: true;
                app_rename?: true;
                app_manage_settings?: true;
                app_manage_users?: true;
                app_approve_user_devices?: true;
                app_manage_cli_users?: true;
                app_read_own_locals?: true;
                app_read_user_locals?: true;
                app_read_user_locals_history?: true;
                app_write_user_locals?: true;
                app_manage_blocks?: true;
                app_manage_environments?: true;
                app_manage_servers?: true;
                app_manage_local_keys?: true;
                app_read_logs?: true;
                app_manage_included_roles?: true;
                app_manage_firewall?: true;
            }>;
        }>;
        environments?: Record<string, {
            users?: Record<string, {
                write?: true;
                write_branches?: true;
                read?: true;
                read_inherits?: true;
                read_meta?: true;
                read_history?: true;
                read_branches?: true;
                read_branches_inherits?: true;
                read_branches_meta?: true;
                read_branches_history?: true;
            }>;
            devices?: Record<string, {
                write?: true;
                write_branches?: true;
                read?: true;
                read_inherits?: true;
                read_meta?: true;
                read_history?: true;
                read_branches?: true;
                read_branches_inherits?: true;
                read_branches_meta?: true;
                read_branches_history?: true;
            }>;
            servers?: Record<string, string>;
            localKeys?: Record<string, string>;
        }>;
    }>, z.ZodUndefined]>;
    removed: z.ZodUnion<[z.ZodObject<{
        org: z.ZodUnion<[z.ZodObject<{
            users: z.ZodUnion<[z.ZodRecord<z.ZodObject<Record<"org_rename" | "org_manage_settings" | "org_manage_auth_settings" | "org_manage_billing" | "org_manage_users" | "org_manage_user_devices" | "org_invite_users_to_permitted_apps" | "org_approve_devices_for_permitted" | "org_manage_cli_users" | "org_create_cli_users_for_permitted_apps" | "org_manage_app_roles" | "org_manage_org_roles" | "org_manage_environment_roles" | "org_manage_teams" | "org_manage_app_groups" | "org_manage_block_groups" | "org_read_logs" | "org_manage_firewall" | "org_generate_recovery_key" | "org_clear_tokens" | "org_archive_import_export" | "org_manage_integrations" | "org_delete" | "apps_create" | "apps_delete" | "apps_read_permitted" | "blocks_create" | "blocks_read_all" | "blocks_rename" | "blocks_manage_settings" | "blocks_write_envs_all" | "blocks_write_envs_permitted" | "blocks_manage_connections_permitted" | "blocks_manage_environments" | "blocks_delete" | "self_hosted_upgrade" | "self_hosted_manage_host" | "self_hosted_read_host_logs", z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>, {
                strict: true;
            }, {
                org_rename?: true;
                org_manage_settings?: true;
                org_manage_auth_settings?: true;
                org_manage_billing?: true;
                org_manage_users?: true;
                org_manage_user_devices?: true;
                org_invite_users_to_permitted_apps?: true;
                org_approve_devices_for_permitted?: true;
                org_manage_cli_users?: true;
                org_create_cli_users_for_permitted_apps?: true;
                org_manage_app_roles?: true;
                org_manage_org_roles?: true;
                org_manage_environment_roles?: true;
                org_manage_teams?: true;
                org_manage_app_groups?: true;
                org_manage_block_groups?: true;
                org_read_logs?: true;
                org_manage_firewall?: true;
                org_generate_recovery_key?: true;
                org_clear_tokens?: true;
                org_archive_import_export?: true;
                org_manage_integrations?: true;
                org_delete?: true;
                apps_create?: true;
                apps_delete?: true;
                apps_read_permitted?: true;
                blocks_create?: true;
                blocks_read_all?: true;
                blocks_rename?: true;
                blocks_manage_settings?: true;
                blocks_write_envs_all?: true;
                blocks_write_envs_permitted?: true;
                blocks_manage_connections_permitted?: true;
                blocks_manage_environments?: true;
                blocks_delete?: true;
                self_hosted_upgrade?: true;
                self_hosted_manage_host?: true;
                self_hosted_read_host_logs?: true;
            }>>, z.ZodUndefined]>;
            devices: z.ZodUnion<[z.ZodRecord<z.ZodObject<Record<"org_rename" | "org_manage_settings" | "org_manage_auth_settings" | "org_manage_billing" | "org_manage_users" | "org_manage_user_devices" | "org_invite_users_to_permitted_apps" | "org_approve_devices_for_permitted" | "org_manage_cli_users" | "org_create_cli_users_for_permitted_apps" | "org_manage_app_roles" | "org_manage_org_roles" | "org_manage_environment_roles" | "org_manage_teams" | "org_manage_app_groups" | "org_manage_block_groups" | "org_read_logs" | "org_manage_firewall" | "org_generate_recovery_key" | "org_clear_tokens" | "org_archive_import_export" | "org_manage_integrations" | "org_delete" | "apps_create" | "apps_delete" | "apps_read_permitted" | "blocks_create" | "blocks_read_all" | "blocks_rename" | "blocks_manage_settings" | "blocks_write_envs_all" | "blocks_write_envs_permitted" | "blocks_manage_connections_permitted" | "blocks_manage_environments" | "blocks_delete" | "self_hosted_upgrade" | "self_hosted_manage_host" | "self_hosted_read_host_logs", z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>, {
                strict: true;
            }, {
                org_rename?: true;
                org_manage_settings?: true;
                org_manage_auth_settings?: true;
                org_manage_billing?: true;
                org_manage_users?: true;
                org_manage_user_devices?: true;
                org_invite_users_to_permitted_apps?: true;
                org_approve_devices_for_permitted?: true;
                org_manage_cli_users?: true;
                org_create_cli_users_for_permitted_apps?: true;
                org_manage_app_roles?: true;
                org_manage_org_roles?: true;
                org_manage_environment_roles?: true;
                org_manage_teams?: true;
                org_manage_app_groups?: true;
                org_manage_block_groups?: true;
                org_read_logs?: true;
                org_manage_firewall?: true;
                org_generate_recovery_key?: true;
                org_clear_tokens?: true;
                org_archive_import_export?: true;
                org_manage_integrations?: true;
                org_delete?: true;
                apps_create?: true;
                apps_delete?: true;
                apps_read_permitted?: true;
                blocks_create?: true;
                blocks_read_all?: true;
                blocks_rename?: true;
                blocks_manage_settings?: true;
                blocks_write_envs_all?: true;
                blocks_write_envs_permitted?: true;
                blocks_manage_connections_permitted?: true;
                blocks_manage_environments?: true;
                blocks_delete?: true;
                self_hosted_upgrade?: true;
                self_hosted_manage_host?: true;
                self_hosted_read_host_logs?: true;
            }>>, z.ZodUndefined]>;
        }, {
            strict: true;
        }, {
            users?: Record<string, {
                org_rename?: true;
                org_manage_settings?: true;
                org_manage_auth_settings?: true;
                org_manage_billing?: true;
                org_manage_users?: true;
                org_manage_user_devices?: true;
                org_invite_users_to_permitted_apps?: true;
                org_approve_devices_for_permitted?: true;
                org_manage_cli_users?: true;
                org_create_cli_users_for_permitted_apps?: true;
                org_manage_app_roles?: true;
                org_manage_org_roles?: true;
                org_manage_environment_roles?: true;
                org_manage_teams?: true;
                org_manage_app_groups?: true;
                org_manage_block_groups?: true;
                org_read_logs?: true;
                org_manage_firewall?: true;
                org_generate_recovery_key?: true;
                org_clear_tokens?: true;
                org_archive_import_export?: true;
                org_manage_integrations?: true;
                org_delete?: true;
                apps_create?: true;
                apps_delete?: true;
                apps_read_permitted?: true;
                blocks_create?: true;
                blocks_read_all?: true;
                blocks_rename?: true;
                blocks_manage_settings?: true;
                blocks_write_envs_all?: true;
                blocks_write_envs_permitted?: true;
                blocks_manage_connections_permitted?: true;
                blocks_manage_environments?: true;
                blocks_delete?: true;
                self_hosted_upgrade?: true;
                self_hosted_manage_host?: true;
                self_hosted_read_host_logs?: true;
            }>;
            devices?: Record<string, {
                org_rename?: true;
                org_manage_settings?: true;
                org_manage_auth_settings?: true;
                org_manage_billing?: true;
                org_manage_users?: true;
                org_manage_user_devices?: true;
                org_invite_users_to_permitted_apps?: true;
                org_approve_devices_for_permitted?: true;
                org_manage_cli_users?: true;
                org_create_cli_users_for_permitted_apps?: true;
                org_manage_app_roles?: true;
                org_manage_org_roles?: true;
                org_manage_environment_roles?: true;
                org_manage_teams?: true;
                org_manage_app_groups?: true;
                org_manage_block_groups?: true;
                org_read_logs?: true;
                org_manage_firewall?: true;
                org_generate_recovery_key?: true;
                org_clear_tokens?: true;
                org_archive_import_export?: true;
                org_manage_integrations?: true;
                org_delete?: true;
                apps_create?: true;
                apps_delete?: true;
                apps_read_permitted?: true;
                blocks_create?: true;
                blocks_read_all?: true;
                blocks_rename?: true;
                blocks_manage_settings?: true;
                blocks_write_envs_all?: true;
                blocks_write_envs_permitted?: true;
                blocks_manage_connections_permitted?: true;
                blocks_manage_environments?: true;
                blocks_delete?: true;
                self_hosted_upgrade?: true;
                self_hosted_manage_host?: true;
                self_hosted_read_host_logs?: true;
            }>;
        }>, z.ZodUndefined]>;
        apps: z.ZodUnion<[z.ZodRecord<z.ZodObject<{
            users: z.ZodUnion<[z.ZodRecord<z.ZodObject<Record<"app_read" | "app_rename" | "app_manage_settings" | "app_manage_users" | "app_approve_user_devices" | "app_manage_cli_users" | "app_read_own_locals" | "app_read_user_locals" | "app_read_user_locals_history" | "app_write_user_locals" | "app_manage_blocks" | "app_manage_environments" | "app_manage_servers" | "app_manage_local_keys" | "app_read_logs" | "app_manage_included_roles" | "app_manage_firewall", z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>, {
                strict: true;
            }, {
                app_read?: true;
                app_rename?: true;
                app_manage_settings?: true;
                app_manage_users?: true;
                app_approve_user_devices?: true;
                app_manage_cli_users?: true;
                app_read_own_locals?: true;
                app_read_user_locals?: true;
                app_read_user_locals_history?: true;
                app_write_user_locals?: true;
                app_manage_blocks?: true;
                app_manage_environments?: true;
                app_manage_servers?: true;
                app_manage_local_keys?: true;
                app_read_logs?: true;
                app_manage_included_roles?: true;
                app_manage_firewall?: true;
            }>>, z.ZodUndefined]>;
            devices: z.ZodUnion<[z.ZodRecord<z.ZodObject<Record<"app_read" | "app_rename" | "app_manage_settings" | "app_manage_users" | "app_approve_user_devices" | "app_manage_cli_users" | "app_read_own_locals" | "app_read_user_locals" | "app_read_user_locals_history" | "app_write_user_locals" | "app_manage_blocks" | "app_manage_environments" | "app_manage_servers" | "app_manage_local_keys" | "app_read_logs" | "app_manage_included_roles" | "app_manage_firewall", z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>, {
                strict: true;
            }, {
                app_read?: true;
                app_rename?: true;
                app_manage_settings?: true;
                app_manage_users?: true;
                app_approve_user_devices?: true;
                app_manage_cli_users?: true;
                app_read_own_locals?: true;
                app_read_user_locals?: true;
                app_read_user_locals_history?: true;
                app_write_user_locals?: true;
                app_manage_blocks?: true;
                app_manage_environments?: true;
                app_manage_servers?: true;
                app_manage_local_keys?: true;
                app_read_logs?: true;
                app_manage_included_roles?: true;
                app_manage_firewall?: true;
            }>>, z.ZodUndefined]>;
        }, {
            strict: true;
        }, {
            users?: Record<string, {
                app_read?: true;
                app_rename?: true;
                app_manage_settings?: true;
                app_manage_users?: true;
                app_approve_user_devices?: true;
                app_manage_cli_users?: true;
                app_read_own_locals?: true;
                app_read_user_locals?: true;
                app_read_user_locals_history?: true;
                app_write_user_locals?: true;
                app_manage_blocks?: true;
                app_manage_environments?: true;
                app_manage_servers?: true;
                app_manage_local_keys?: true;
                app_read_logs?: true;
                app_manage_included_roles?: true;
                app_manage_firewall?: true;
            }>;
            devices?: Record<string, {
                app_read?: true;
                app_rename?: true;
                app_manage_settings?: true;
                app_manage_users?: true;
                app_approve_user_devices?: true;
                app_manage_cli_users?: true;
                app_read_own_locals?: true;
                app_read_user_locals?: true;
                app_read_user_locals_history?: true;
                app_write_user_locals?: true;
                app_manage_blocks?: true;
                app_manage_environments?: true;
                app_manage_servers?: true;
                app_manage_local_keys?: true;
                app_read_logs?: true;
                app_manage_included_roles?: true;
                app_manage_firewall?: true;
            }>;
        }>>, z.ZodUndefined]>;
        environments: z.ZodUnion<[z.ZodRecord<z.ZodObject<{
            servers: z.ZodUnion<[z.ZodRecord<z.ZodString>, z.ZodUndefined]>;
            localKeys: z.ZodUnion<[z.ZodRecord<z.ZodString>, z.ZodUndefined]>;
            users: z.ZodUnion<[z.ZodRecord<z.ZodObject<Record<"write" | "write_branches" | "read" | "read_inherits" | "read_meta" | "read_history" | "read_branches" | "read_branches_inherits" | "read_branches_meta" | "read_branches_history", z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>, {
                strict: true;
            }, {
                write?: true;
                write_branches?: true;
                read?: true;
                read_inherits?: true;
                read_meta?: true;
                read_history?: true;
                read_branches?: true;
                read_branches_inherits?: true;
                read_branches_meta?: true;
                read_branches_history?: true;
            }>>, z.ZodUndefined]>;
            devices: z.ZodUnion<[z.ZodRecord<z.ZodObject<Record<"write" | "write_branches" | "read" | "read_inherits" | "read_meta" | "read_history" | "read_branches" | "read_branches_inherits" | "read_branches_meta" | "read_branches_history", z.ZodUnion<[z.ZodLiteral<true>, z.ZodUndefined]>>, {
                strict: true;
            }, {
                write?: true;
                write_branches?: true;
                read?: true;
                read_inherits?: true;
                read_meta?: true;
                read_history?: true;
                read_branches?: true;
                read_branches_inherits?: true;
                read_branches_meta?: true;
                read_branches_history?: true;
            }>>, z.ZodUndefined]>;
        }, {
            strict: true;
        }, {
            users?: Record<string, {
                write?: true;
                write_branches?: true;
                read?: true;
                read_inherits?: true;
                read_meta?: true;
                read_history?: true;
                read_branches?: true;
                read_branches_inherits?: true;
                read_branches_meta?: true;
                read_branches_history?: true;
            }>;
            devices?: Record<string, {
                write?: true;
                write_branches?: true;
                read?: true;
                read_inherits?: true;
                read_meta?: true;
                read_history?: true;
                read_branches?: true;
                read_branches_inherits?: true;
                read_branches_meta?: true;
                read_branches_history?: true;
            }>;
            servers?: Record<string, string>;
            localKeys?: Record<string, string>;
        }>>, z.ZodUndefined]>;
    }, {
        strict: true;
    }, {
        org?: {
            users?: Record<string, {
                org_rename?: true;
                org_manage_settings?: true;
                org_manage_auth_settings?: true;
                org_manage_billing?: true;
                org_manage_users?: true;
                org_manage_user_devices?: true;
                org_invite_users_to_permitted_apps?: true;
                org_approve_devices_for_permitted?: true;
                org_manage_cli_users?: true;
                org_create_cli_users_for_permitted_apps?: true;
                org_manage_app_roles?: true;
                org_manage_org_roles?: true;
                org_manage_environment_roles?: true;
                org_manage_teams?: true;
                org_manage_app_groups?: true;
                org_manage_block_groups?: true;
                org_read_logs?: true;
                org_manage_firewall?: true;
                org_generate_recovery_key?: true;
                org_clear_tokens?: true;
                org_archive_import_export?: true;
                org_manage_integrations?: true;
                org_delete?: true;
                apps_create?: true;
                apps_delete?: true;
                apps_read_permitted?: true;
                blocks_create?: true;
                blocks_read_all?: true;
                blocks_rename?: true;
                blocks_manage_settings?: true;
                blocks_write_envs_all?: true;
                blocks_write_envs_permitted?: true;
                blocks_manage_connections_permitted?: true;
                blocks_manage_environments?: true;
                blocks_delete?: true;
                self_hosted_upgrade?: true;
                self_hosted_manage_host?: true;
                self_hosted_read_host_logs?: true;
            }>;
            devices?: Record<string, {
                org_rename?: true;
                org_manage_settings?: true;
                org_manage_auth_settings?: true;
                org_manage_billing?: true;
                org_manage_users?: true;
                org_manage_user_devices?: true;
                org_invite_users_to_permitted_apps?: true;
                org_approve_devices_for_permitted?: true;
                org_manage_cli_users?: true;
                org_create_cli_users_for_permitted_apps?: true;
                org_manage_app_roles?: true;
                org_manage_org_roles?: true;
                org_manage_environment_roles?: true;
                org_manage_teams?: true;
                org_manage_app_groups?: true;
                org_manage_block_groups?: true;
                org_read_logs?: true;
                org_manage_firewall?: true;
                org_generate_recovery_key?: true;
                org_clear_tokens?: true;
                org_archive_import_export?: true;
                org_manage_integrations?: true;
                org_delete?: true;
                apps_create?: true;
                apps_delete?: true;
                apps_read_permitted?: true;
                blocks_create?: true;
                blocks_read_all?: true;
                blocks_rename?: true;
                blocks_manage_settings?: true;
                blocks_write_envs_all?: true;
                blocks_write_envs_permitted?: true;
                blocks_manage_connections_permitted?: true;
                blocks_manage_environments?: true;
                blocks_delete?: true;
                self_hosted_upgrade?: true;
                self_hosted_manage_host?: true;
                self_hosted_read_host_logs?: true;
            }>;
        };
        apps?: Record<string, {
            users?: Record<string, {
                app_read?: true;
                app_rename?: true;
                app_manage_settings?: true;
                app_manage_users?: true;
                app_approve_user_devices?: true;
                app_manage_cli_users?: true;
                app_read_own_locals?: true;
                app_read_user_locals?: true;
                app_read_user_locals_history?: true;
                app_write_user_locals?: true;
                app_manage_blocks?: true;
                app_manage_environments?: true;
                app_manage_servers?: true;
                app_manage_local_keys?: true;
                app_read_logs?: true;
                app_manage_included_roles?: true;
                app_manage_firewall?: true;
            }>;
            devices?: Record<string, {
                app_read?: true;
                app_rename?: true;
                app_manage_settings?: true;
                app_manage_users?: true;
                app_approve_user_devices?: true;
                app_manage_cli_users?: true;
                app_read_own_locals?: true;
                app_read_user_locals?: true;
                app_read_user_locals_history?: true;
                app_write_user_locals?: true;
                app_manage_blocks?: true;
                app_manage_environments?: true;
                app_manage_servers?: true;
                app_manage_local_keys?: true;
                app_read_logs?: true;
                app_manage_included_roles?: true;
                app_manage_firewall?: true;
            }>;
        }>;
        environments?: Record<string, {
            users?: Record<string, {
                write?: true;
                write_branches?: true;
                read?: true;
                read_inherits?: true;
                read_meta?: true;
                read_history?: true;
                read_branches?: true;
                read_branches_inherits?: true;
                read_branches_meta?: true;
                read_branches_history?: true;
            }>;
            devices?: Record<string, {
                write?: true;
                write_branches?: true;
                read?: true;
                read_inherits?: true;
                read_meta?: true;
                read_history?: true;
                read_branches?: true;
                read_branches_inherits?: true;
                read_branches_meta?: true;
                read_branches_history?: true;
            }>;
            servers?: Record<string, string>;
            localKeys?: Record<string, string>;
        }>;
    }>, z.ZodUndefined]>;
}, {
    strict: true;
}, {
    granted?: {
        org?: {
            users?: Record<string, {
                org_rename?: true;
                org_manage_settings?: true;
                org_manage_auth_settings?: true;
                org_manage_billing?: true;
                org_manage_users?: true;
                org_manage_user_devices?: true;
                org_invite_users_to_permitted_apps?: true;
                org_approve_devices_for_permitted?: true;
                org_manage_cli_users?: true;
                org_create_cli_users_for_permitted_apps?: true;
                org_manage_app_roles?: true;
                org_manage_org_roles?: true;
                org_manage_environment_roles?: true;
                org_manage_teams?: true;
                org_manage_app_groups?: true;
                org_manage_block_groups?: true;
                org_read_logs?: true;
                org_manage_firewall?: true;
                org_generate_recovery_key?: true;
                org_clear_tokens?: true;
                org_archive_import_export?: true;
                org_manage_integrations?: true;
                org_delete?: true;
                apps_create?: true;
                apps_delete?: true;
                apps_read_permitted?: true;
                blocks_create?: true;
                blocks_read_all?: true;
                blocks_rename?: true;
                blocks_manage_settings?: true;
                blocks_write_envs_all?: true;
                blocks_write_envs_permitted?: true;
                blocks_manage_connections_permitted?: true;
                blocks_manage_environments?: true;
                blocks_delete?: true;
                self_hosted_upgrade?: true;
                self_hosted_manage_host?: true;
                self_hosted_read_host_logs?: true;
            }>;
            devices?: Record<string, {
                org_rename?: true;
                org_manage_settings?: true;
                org_manage_auth_settings?: true;
                org_manage_billing?: true;
                org_manage_users?: true;
                org_manage_user_devices?: true;
                org_invite_users_to_permitted_apps?: true;
                org_approve_devices_for_permitted?: true;
                org_manage_cli_users?: true;
                org_create_cli_users_for_permitted_apps?: true;
                org_manage_app_roles?: true;
                org_manage_org_roles?: true;
                org_manage_environment_roles?: true;
                org_manage_teams?: true;
                org_manage_app_groups?: true;
                org_manage_block_groups?: true;
                org_read_logs?: true;
                org_manage_firewall?: true;
                org_generate_recovery_key?: true;
                org_clear_tokens?: true;
                org_archive_import_export?: true;
                org_manage_integrations?: true;
                org_delete?: true;
                apps_create?: true;
                apps_delete?: true;
                apps_read_permitted?: true;
                blocks_create?: true;
                blocks_read_all?: true;
                blocks_rename?: true;
                blocks_manage_settings?: true;
                blocks_write_envs_all?: true;
                blocks_write_envs_permitted?: true;
                blocks_manage_connections_permitted?: true;
                blocks_manage_environments?: true;
                blocks_delete?: true;
                self_hosted_upgrade?: true;
                self_hosted_manage_host?: true;
                self_hosted_read_host_logs?: true;
            }>;
        };
        apps?: Record<string, {
            users?: Record<string, {
                app_read?: true;
                app_rename?: true;
                app_manage_settings?: true;
                app_manage_users?: true;
                app_approve_user_devices?: true;
                app_manage_cli_users?: true;
                app_read_own_locals?: true;
                app_read_user_locals?: true;
                app_read_user_locals_history?: true;
                app_write_user_locals?: true;
                app_manage_blocks?: true;
                app_manage_environments?: true;
                app_manage_servers?: true;
                app_manage_local_keys?: true;
                app_read_logs?: true;
                app_manage_included_roles?: true;
                app_manage_firewall?: true;
            }>;
            devices?: Record<string, {
                app_read?: true;
                app_rename?: true;
                app_manage_settings?: true;
                app_manage_users?: true;
                app_approve_user_devices?: true;
                app_manage_cli_users?: true;
                app_read_own_locals?: true;
                app_read_user_locals?: true;
                app_read_user_locals_history?: true;
                app_write_user_locals?: true;
                app_manage_blocks?: true;
                app_manage_environments?: true;
                app_manage_servers?: true;
                app_manage_local_keys?: true;
                app_read_logs?: true;
                app_manage_included_roles?: true;
                app_manage_firewall?: true;
            }>;
        }>;
        environments?: Record<string, {
            users?: Record<string, {
                write?: true;
                write_branches?: true;
                read?: true;
                read_inherits?: true;
                read_meta?: true;
                read_history?: true;
                read_branches?: true;
                read_branches_inherits?: true;
                read_branches_meta?: true;
                read_branches_history?: true;
            }>;
            devices?: Record<string, {
                write?: true;
                write_branches?: true;
                read?: true;
                read_inherits?: true;
                read_meta?: true;
                read_history?: true;
                read_branches?: true;
                read_branches_inherits?: true;
                read_branches_meta?: true;
                read_branches_history?: true;
            }>;
            servers?: Record<string, string>;
            localKeys?: Record<string, string>;
        }>;
    };
    removed?: {
        org?: {
            users?: Record<string, {
                org_rename?: true;
                org_manage_settings?: true;
                org_manage_auth_settings?: true;
                org_manage_billing?: true;
                org_manage_users?: true;
                org_manage_user_devices?: true;
                org_invite_users_to_permitted_apps?: true;
                org_approve_devices_for_permitted?: true;
                org_manage_cli_users?: true;
                org_create_cli_users_for_permitted_apps?: true;
                org_manage_app_roles?: true;
                org_manage_org_roles?: true;
                org_manage_environment_roles?: true;
                org_manage_teams?: true;
                org_manage_app_groups?: true;
                org_manage_block_groups?: true;
                org_read_logs?: true;
                org_manage_firewall?: true;
                org_generate_recovery_key?: true;
                org_clear_tokens?: true;
                org_archive_import_export?: true;
                org_manage_integrations?: true;
                org_delete?: true;
                apps_create?: true;
                apps_delete?: true;
                apps_read_permitted?: true;
                blocks_create?: true;
                blocks_read_all?: true;
                blocks_rename?: true;
                blocks_manage_settings?: true;
                blocks_write_envs_all?: true;
                blocks_write_envs_permitted?: true;
                blocks_manage_connections_permitted?: true;
                blocks_manage_environments?: true;
                blocks_delete?: true;
                self_hosted_upgrade?: true;
                self_hosted_manage_host?: true;
                self_hosted_read_host_logs?: true;
            }>;
            devices?: Record<string, {
                org_rename?: true;
                org_manage_settings?: true;
                org_manage_auth_settings?: true;
                org_manage_billing?: true;
                org_manage_users?: true;
                org_manage_user_devices?: true;
                org_invite_users_to_permitted_apps?: true;
                org_approve_devices_for_permitted?: true;
                org_manage_cli_users?: true;
                org_create_cli_users_for_permitted_apps?: true;
                org_manage_app_roles?: true;
                org_manage_org_roles?: true;
                org_manage_environment_roles?: true;
                org_manage_teams?: true;
                org_manage_app_groups?: true;
                org_manage_block_groups?: true;
                org_read_logs?: true;
                org_manage_firewall?: true;
                org_generate_recovery_key?: true;
                org_clear_tokens?: true;
                org_archive_import_export?: true;
                org_manage_integrations?: true;
                org_delete?: true;
                apps_create?: true;
                apps_delete?: true;
                apps_read_permitted?: true;
                blocks_create?: true;
                blocks_read_all?: true;
                blocks_rename?: true;
                blocks_manage_settings?: true;
                blocks_write_envs_all?: true;
                blocks_write_envs_permitted?: true;
                blocks_manage_connections_permitted?: true;
                blocks_manage_environments?: true;
                blocks_delete?: true;
                self_hosted_upgrade?: true;
                self_hosted_manage_host?: true;
                self_hosted_read_host_logs?: true;
            }>;
        };
        apps?: Record<string, {
            users?: Record<string, {
                app_read?: true;
                app_rename?: true;
                app_manage_settings?: true;
                app_manage_users?: true;
                app_approve_user_devices?: true;
                app_manage_cli_users?: true;
                app_read_own_locals?: true;
                app_read_user_locals?: true;
                app_read_user_locals_history?: true;
                app_write_user_locals?: true;
                app_manage_blocks?: true;
                app_manage_environments?: true;
                app_manage_servers?: true;
                app_manage_local_keys?: true;
                app_read_logs?: true;
                app_manage_included_roles?: true;
                app_manage_firewall?: true;
            }>;
            devices?: Record<string, {
                app_read?: true;
                app_rename?: true;
                app_manage_settings?: true;
                app_manage_users?: true;
                app_approve_user_devices?: true;
                app_manage_cli_users?: true;
                app_read_own_locals?: true;
                app_read_user_locals?: true;
                app_read_user_locals_history?: true;
                app_write_user_locals?: true;
                app_manage_blocks?: true;
                app_manage_environments?: true;
                app_manage_servers?: true;
                app_manage_local_keys?: true;
                app_read_logs?: true;
                app_manage_included_roles?: true;
                app_manage_firewall?: true;
            }>;
        }>;
        environments?: Record<string, {
            users?: Record<string, {
                write?: true;
                write_branches?: true;
                read?: true;
                read_inherits?: true;
                read_meta?: true;
                read_history?: true;
                read_branches?: true;
                read_branches_inherits?: true;
                read_branches_meta?: true;
                read_branches_history?: true;
            }>;
            devices?: Record<string, {
                write?: true;
                write_branches?: true;
                read?: true;
                read_inherits?: true;
                read_meta?: true;
                read_history?: true;
                read_branches?: true;
                read_branches_inherits?: true;
                read_branches_meta?: true;
                read_branches_history?: true;
            }>;
            servers?: Record<string, string>;
            localKeys?: Record<string, string>;
        }>;
    };
}>;
export type OrgAccessUpdated = z.infer<typeof OrgAccessUpdatedSchema>;
//# sourceMappingURL=org_access.d.ts.map