import { Graph } from "../../../../types";
export declare const getServerCreatableEnvironments: ((graph: Graph.Graph, currentUserId: string, appId: string) => ({
    type?: "environment";
    id?: string;
    importId?: string;
    createdAt?: number;
    updatedAt?: number;
    deletedAt?: number;
    "upgradedCrypto-2.1.0"?: boolean;
    environmentRoleId?: string;
    envParentId?: string;
    envUpdatedAt?: number;
    encryptedById?: string;
    reencryptionRequiredAt?: number;
    requiresReinit?: boolean;
} & ({
    settings?: {
        autoCommit?: boolean;
    };
    isSub?: false;
} | {
    isSub?: true;
    parentEnvironmentId?: string;
    subName?: string;
}))[]) & import("memoizee").Memoized<(graph: Graph.Graph, currentUserId: string, appId: string) => ({
    type?: "environment";
    id?: string;
    importId?: string;
    createdAt?: number;
    updatedAt?: number;
    deletedAt?: number;
    "upgradedCrypto-2.1.0"?: boolean;
    environmentRoleId?: string;
    envParentId?: string;
    envUpdatedAt?: number;
    encryptedById?: string;
    reencryptionRequiredAt?: number;
    requiresReinit?: boolean;
} & ({
    settings?: {
        autoCommit?: boolean;
    };
    isSub?: false;
} | {
    isSub?: true;
    parentEnvironmentId?: string;
    subName?: string;
}))[]>, getLocalKeyCreatableEnvironments: ((graph: Graph.Graph, currentUserId: string, appId: string) => ({
    type?: "environment";
    id?: string;
    importId?: string;
    createdAt?: number;
    updatedAt?: number;
    deletedAt?: number;
    "upgradedCrypto-2.1.0"?: boolean;
    environmentRoleId?: string;
    envParentId?: string;
    envUpdatedAt?: number;
    encryptedById?: string;
    reencryptionRequiredAt?: number;
    requiresReinit?: boolean;
} & ({
    settings?: {
        autoCommit?: boolean;
    };
    isSub?: false;
} | {
    isSub?: true;
    parentEnvironmentId?: string;
    subName?: string;
}))[]) & import("memoizee").Memoized<(graph: Graph.Graph, currentUserId: string, appId: string) => ({
    type?: "environment";
    id?: string;
    importId?: string;
    createdAt?: number;
    updatedAt?: number;
    deletedAt?: number;
    "upgradedCrypto-2.1.0"?: boolean;
    environmentRoleId?: string;
    envParentId?: string;
    envUpdatedAt?: number;
    encryptedById?: string;
    reencryptionRequiredAt?: number;
    requiresReinit?: boolean;
} & ({
    settings?: {
        autoCommit?: boolean;
    };
    isSub?: false;
} | {
    isSub?: true;
    parentEnvironmentId?: string;
    subName?: string;
}))[]>, getDeletableServers: ((graph: Graph.Graph, currentUserId: string, appId: string) => {
    type?: "server";
    id?: string;
    importId?: string;
    createdAt?: number;
    updatedAt?: number;
    deletedAt?: number;
    name?: string;
    appId?: string;
    environmentId?: string;
}[]) & import("memoizee").Memoized<(graph: Graph.Graph, currentUserId: string, appId: string) => {
    type?: "server";
    id?: string;
    importId?: string;
    createdAt?: number;
    updatedAt?: number;
    deletedAt?: number;
    name?: string;
    appId?: string;
    environmentId?: string;
}[]>, getDeletableLocalKeys: ((graph: Graph.Graph, currentUserId: string, appId: string) => {
    type?: "localKey";
    userId?: string;
    deviceId?: string;
    id?: string;
    importId?: string;
    createdAt?: number;
    updatedAt?: number;
    deletedAt?: number;
    name?: string;
    appId?: string;
    environmentId?: string;
    autoGenerated?: true;
    isV1UpgradeKey?: true;
}[]) & import("memoizee").Memoized<(graph: Graph.Graph, currentUserId: string, appId: string) => {
    type?: "localKey";
    userId?: string;
    deviceId?: string;
    id?: string;
    importId?: string;
    createdAt?: number;
    updatedAt?: number;
    deletedAt?: number;
    name?: string;
    appId?: string;
    environmentId?: string;
    autoGenerated?: true;
    isV1UpgradeKey?: true;
}[]>, getKeyGeneratableServers: ((graph: Graph.Graph, currentUserId: string, appId: string) => {
    type?: "server";
    id?: string;
    importId?: string;
    createdAt?: number;
    updatedAt?: number;
    deletedAt?: number;
    name?: string;
    appId?: string;
    environmentId?: string;
}[]) & import("memoizee").Memoized<(graph: Graph.Graph, currentUserId: string, appId: string) => {
    type?: "server";
    id?: string;
    importId?: string;
    createdAt?: number;
    updatedAt?: number;
    deletedAt?: number;
    name?: string;
    appId?: string;
    environmentId?: string;
}[]>, getKeyGeneratableLocalKeys: ((graph: Graph.Graph, currentUserId: string, appId: string) => {
    type?: "localKey";
    userId?: string;
    deviceId?: string;
    id?: string;
    importId?: string;
    createdAt?: number;
    updatedAt?: number;
    deletedAt?: number;
    name?: string;
    appId?: string;
    environmentId?: string;
    autoGenerated?: true;
    isV1UpgradeKey?: true;
}[]) & import("memoizee").Memoized<(graph: Graph.Graph, currentUserId: string, appId: string) => {
    type?: "localKey";
    userId?: string;
    deviceId?: string;
    id?: string;
    importId?: string;
    createdAt?: number;
    updatedAt?: number;
    deletedAt?: number;
    name?: string;
    appId?: string;
    environmentId?: string;
    autoGenerated?: true;
    isV1UpgradeKey?: true;
}[]>, getKeyRevokableServers: ((graph: Graph.Graph, currentUserId: string, appId: string) => {
    type?: "server";
    id?: string;
    importId?: string;
    createdAt?: number;
    updatedAt?: number;
    deletedAt?: number;
    name?: string;
    appId?: string;
    environmentId?: string;
}[]) & import("memoizee").Memoized<(graph: Graph.Graph, currentUserId: string, appId: string) => {
    type?: "server";
    id?: string;
    importId?: string;
    createdAt?: number;
    updatedAt?: number;
    deletedAt?: number;
    name?: string;
    appId?: string;
    environmentId?: string;
}[]>, getKeyRevokableLocalKeys: ((graph: Graph.Graph, currentUserId: string, appId: string) => {
    type?: "localKey";
    userId?: string;
    deviceId?: string;
    id?: string;
    importId?: string;
    createdAt?: number;
    updatedAt?: number;
    deletedAt?: number;
    name?: string;
    appId?: string;
    environmentId?: string;
    autoGenerated?: true;
    isV1UpgradeKey?: true;
}[]) & import("memoizee").Memoized<(graph: Graph.Graph, currentUserId: string, appId: string) => {
    type?: "localKey";
    userId?: string;
    deviceId?: string;
    id?: string;
    importId?: string;
    createdAt?: number;
    updatedAt?: number;
    deletedAt?: number;
    name?: string;
    appId?: string;
    environmentId?: string;
    autoGenerated?: true;
    isV1UpgradeKey?: true;
}[]>, getAppsPassingKeyableTest: (graph: Graph.Graph, currentUserId: string, test: (graph: Graph.Graph, currentUserId: string, keyableParentId: string) => boolean) => {
    type?: "app";
    id?: string;
    importId?: string;
    createdAt?: number;
    updatedAt?: number;
    deletedAt?: number;
    name?: string;
    settings?: {
        autoCommitLocals?: boolean;
        autoCaps?: boolean;
    };
    environmentRoleIpsAllowed?: Record<string, string[]>;
    environmentRoleIpsMergeStrategies?: Record<string, "extend" | "override">;
    envsUpdatedAt?: number;
    localsUpdatedAtByUserId?: Record<string, number>;
    localsUpdatedAt?: number;
    localsEncryptedBy?: Record<string, string>;
    localsReencryptionRequiredAt?: Record<string, number>;
    envsOrLocalsUpdatedAt?: number;
    localsRequireReinit?: boolean;
}[];
//# sourceMappingURL=keyable_parents.d.ts.map