#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR/../..

echo "Running envkeygo tests..."
(cd sdks/envkeygo && go test ./...)

echo "Running envkey-node tests..."
(cd public/sdks/languages-and-frameworks/node/pkg && pnpm test)

echo "Running envkey-python tests..."
(cd public/sdks/languages-and-frameworks/python/pkg && make test)

echo "Running envkey-ruby tests..."
(cd public/sdks/languages-and-frameworks/ruby/pkg && rake)

echo "Running envkey-php tests..."
(cd public/sdks/languages-and-frameworks/php && ENVKEY_DISABLE_AUTOLOAD=1 vendor/bin/phpunit tests/EnvkeyTest.php)