import { Graph } from "../../types";
export declare const getOrphanedLocalKeyIdsForUser: (graph: Graph.Graph, userId: string) => string[], getOrphanedLocalKeyIds: (graph: Graph.Graph) => string[], getOrphanedRecoveryKeyIds: (graph: Graph.Graph) => string[], getAllConnectedKeyableParents: ((graph: Graph.Graph, environmentId: string) => ({
    type?: "server";
    id?: string;
    importId?: string;
    createdAt?: number;
    updatedAt?: number;
    deletedAt?: number;
    name?: string;
    appId?: string;
    environmentId?: string;
} | {
    type?: "localKey";
    userId?: string;
    deviceId?: string;
    id?: string;
    importId?: string;
    createdAt?: number;
    updatedAt?: number;
    deletedAt?: number;
    name?: string;
    appId?: string;
    environmentId?: string;
    autoGenerated?: true;
    isV1UpgradeKey?: true;
})[]) & import("memoizee").Memoized<(graph: Graph.Graph, environmentId: string) => ({
    type?: "server";
    id?: string;
    importId?: string;
    createdAt?: number;
    updatedAt?: number;
    deletedAt?: number;
    name?: string;
    appId?: string;
    environmentId?: string;
} | {
    type?: "localKey";
    userId?: string;
    deviceId?: string;
    id?: string;
    importId?: string;
    createdAt?: number;
    updatedAt?: number;
    deletedAt?: number;
    name?: string;
    appId?: string;
    environmentId?: string;
    autoGenerated?: true;
    isV1UpgradeKey?: true;
})[]>, getConnectedActiveGeneratedEnvkeys: ((graph: Graph.Graph, environmentId: string) => {
    type?: "generatedEnvkey";
    pubkey?: {
        keys?: {
            signingKey?: string;
            encryptionKey?: string;
        };
        signature?: string;
    };
    id?: string;
    createdAt?: number;
    updatedAt?: number;
    deletedAt?: number;
    creatorId?: string;
    pubkeyId?: string;
    pubkeyUpdatedAt?: number;
    signedById?: string;
    creatorDeviceId?: string;
    appId?: string;
    environmentId?: string;
    keyableParentId?: string;
    keyableParentType?: "server" | "localKey";
    envkeyShort?: string;
    envkeyIdPartHash?: string;
    blobsUpdatedAt?: number;
}[]) & import("memoizee").Memoized<(graph: Graph.Graph, environmentId: string) => {
    type?: "generatedEnvkey";
    pubkey?: {
        keys?: {
            signingKey?: string;
            encryptionKey?: string;
        };
        signature?: string;
    };
    id?: string;
    createdAt?: number;
    updatedAt?: number;
    deletedAt?: number;
    creatorId?: string;
    pubkeyId?: string;
    pubkeyUpdatedAt?: number;
    signedById?: string;
    creatorDeviceId?: string;
    appId?: string;
    environmentId?: string;
    keyableParentId?: string;
    keyableParentType?: "server" | "localKey";
    envkeyShort?: string;
    envkeyIdPartHash?: string;
    blobsUpdatedAt?: number;
}[]>;
//# sourceMappingURL=keyable_parents.d.ts.map