import { Graph, Rbac } from "../../types";
export declare const getOrgAccessSet: (graph: Graph.Graph, scope: Rbac.OrgAccessScope) => {
    org?: {
        users?: Record<string, {
            org_rename?: true;
            org_manage_settings?: true;
            org_manage_auth_settings?: true;
            org_manage_billing?: true;
            org_manage_users?: true;
            org_manage_user_devices?: true;
            org_invite_users_to_permitted_apps?: true;
            org_approve_devices_for_permitted?: true;
            org_manage_cli_users?: true;
            org_create_cli_users_for_permitted_apps?: true;
            org_manage_app_roles?: true;
            org_manage_org_roles?: true;
            org_manage_environment_roles?: true;
            org_manage_teams?: true;
            org_manage_app_groups?: true;
            org_manage_block_groups?: true;
            org_read_logs?: true;
            org_manage_firewall?: true;
            org_generate_recovery_key?: true;
            org_clear_tokens?: true;
            org_archive_import_export?: true;
            org_manage_integrations?: true;
            org_delete?: true;
            apps_create?: true;
            apps_delete?: true;
            apps_read_permitted?: true;
            blocks_create?: true;
            blocks_read_all?: true;
            blocks_rename?: true;
            blocks_manage_settings?: true;
            blocks_write_envs_all?: true;
            blocks_write_envs_permitted?: true;
            blocks_manage_connections_permitted?: true;
            blocks_manage_environments?: true;
            blocks_delete?: true;
            self_hosted_upgrade?: true;
            self_hosted_manage_host?: true;
            self_hosted_read_host_logs?: true;
        }>;
        devices?: Record<string, {
            org_rename?: true;
            org_manage_settings?: true;
            org_manage_auth_settings?: true;
            org_manage_billing?: true;
            org_manage_users?: true;
            org_manage_user_devices?: true;
            org_invite_users_to_permitted_apps?: true;
            org_approve_devices_for_permitted?: true;
            org_manage_cli_users?: true;
            org_create_cli_users_for_permitted_apps?: true;
            org_manage_app_roles?: true;
            org_manage_org_roles?: true;
            org_manage_environment_roles?: true;
            org_manage_teams?: true;
            org_manage_app_groups?: true;
            org_manage_block_groups?: true;
            org_read_logs?: true;
            org_manage_firewall?: true;
            org_generate_recovery_key?: true;
            org_clear_tokens?: true;
            org_archive_import_export?: true;
            org_manage_integrations?: true;
            org_delete?: true;
            apps_create?: true;
            apps_delete?: true;
            apps_read_permitted?: true;
            blocks_create?: true;
            blocks_read_all?: true;
            blocks_rename?: true;
            blocks_manage_settings?: true;
            blocks_write_envs_all?: true;
            blocks_write_envs_permitted?: true;
            blocks_manage_connections_permitted?: true;
            blocks_manage_environments?: true;
            blocks_delete?: true;
            self_hosted_upgrade?: true;
            self_hosted_manage_host?: true;
            self_hosted_read_host_logs?: true;
        }>;
    };
    apps?: Record<string, {
        users?: Record<string, {
            app_read?: true;
            app_rename?: true;
            app_manage_settings?: true;
            app_manage_users?: true;
            app_approve_user_devices?: true;
            app_manage_cli_users?: true;
            app_read_own_locals?: true;
            app_read_user_locals?: true;
            app_read_user_locals_history?: true;
            app_write_user_locals?: true;
            app_manage_blocks?: true;
            app_manage_environments?: true;
            app_manage_servers?: true;
            app_manage_local_keys?: true;
            app_read_logs?: true;
            app_manage_included_roles?: true;
            app_manage_firewall?: true;
        }>;
        devices?: Record<string, {
            app_read?: true;
            app_rename?: true;
            app_manage_settings?: true;
            app_manage_users?: true;
            app_approve_user_devices?: true;
            app_manage_cli_users?: true;
            app_read_own_locals?: true;
            app_read_user_locals?: true;
            app_read_user_locals_history?: true;
            app_write_user_locals?: true;
            app_manage_blocks?: true;
            app_manage_environments?: true;
            app_manage_servers?: true;
            app_manage_local_keys?: true;
            app_read_logs?: true;
            app_manage_included_roles?: true;
            app_manage_firewall?: true;
        }>;
    }>;
    environments?: Record<string, {
        users?: Record<string, {
            write?: true;
            write_branches?: true;
            read?: true;
            read_inherits?: true;
            read_meta?: true;
            read_history?: true;
            read_branches?: true;
            read_branches_inherits?: true;
            read_branches_meta?: true;
            read_branches_history?: true;
        }>;
        devices?: Record<string, {
            write?: true;
            write_branches?: true;
            read?: true;
            read_inherits?: true;
            read_meta?: true;
            read_history?: true;
            read_branches?: true;
            read_branches_inherits?: true;
            read_branches_meta?: true;
            read_branches_history?: true;
        }>;
        servers?: Record<string, string>;
        localKeys?: Record<string, string>;
    }>;
};
export declare const mergeAccessScopes: (...sets: Rbac.OrgAccessScope[]) => Rbac.OrgAccessScope;
//# sourceMappingURL=org_access.d.ts.map