"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CRYPTO_SYMMETRIC_STATUS_INTERVAL = exports.CRYPTO_SYMMETRIC_BATCH_DELAY_MS = exports.CRYPTO_SYMMETRIC_BATCH_SIZE = exports.CRYPTO_ASYMMETRIC_STATUS_INTERVAL = exports.CRYPTO_ASYMMETRIC_BATCH_DELAY_MS = exports.CRYPTO_ASYMMETRIC_BATCH_SIZE = void 0;
exports.CRYPTO_ASYMMETRIC_BATCH_SIZE = 500;
exports.CRYPTO_ASYMMETRIC_BATCH_DELAY_MS = 70;
exports.CRYPTO_ASYMMETRIC_STATUS_INTERVAL = 100;
exports.CRYPTO_SYMMETRIC_BATCH_SIZE = 500;
exports.CRYPTO_SYMMETRIC_BATCH_DELAY_MS = 70;
exports.CRYPTO_SYMMETRIC_STATUS_INTERVAL = 100;
//# sourceMappingURL=constants.js.map